[package]
name = "changebase"
authors = ["Mark Toda"]
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "changebase"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.44"
clap = "2.33.3"
num = "0.4.0"
structopt = "0.3.22"
thiserror = "1.0.30"
